{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "config_ollama_mistral = [\n",
    "    {\n",
    "        \"model\": \"NotRequired\",  # Loaded with LiteLLM command\n",
    "        \"api_key\": \"NotRequired\",  # Not needed\n",
    "        \"base_url\": \"http://0.0.0.0:4000\",  # Your LiteLLM URL\n",
    "        \"price\": [0, 0],\n",
    "    }\n",
    "]\n",
    "\n",
    "llm_mistral = {\n",
    "    \"seed\": 25,\n",
    "    \"temperature\": 0,\n",
    "    \"config_list\": config_ollama_mistral,\n",
    "    }\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "from autogen import ConversableAgent\n",
    "from autogen import AssistantAgent, UserProxyAgent\n",
    "from autogen.agentchat.contrib.retrieve_user_proxy_agent import RetrieveUserProxyAgent"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/niel77/miniconda3/envs/magents/lib/python3.12/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884\n",
      "  warnings.warn(\n"
     ]
    }
   ],
   "source": [
    "user_proxy = UserProxyAgent(\n",
    "    name=\"user_proxy\",\n",
    "    human_input_mode=\"NEVER\",\n",
    "    max_consecutive_auto_reply=10,\n",
    "    code_execution_config={\n",
    "        \"work_dir\": \"NewCAD\",\n",
    "        \"use_docker\": False,\n",
    "    },\n",
    ")\n",
    "\n",
    "system_message=\"\"\"You are a Cadquery code writer that retrieves the relevant code from the given context to create CAD models.\n",
    "            Write your code script in Markdown format. For example:\n",
    "```python\n",
    "import cadquery as cq\n",
    "from ocp_vscode import \n",
    "...\n",
    "```\n",
    "        The code provided will be executed in the order it is written. If a code block fails to execute try to fix the error and write the code block again.\n",
    "        Once all code blocks are successfully executed, return 'TERMINATE' to end the conversation.\n",
    "        \"\"\"\n",
    "import chromadb\n",
    "from autogen.agentchat.contrib.retrieve_user_proxy_agent import RetrieveUserProxyAgent\n",
    "rag_agent = RetrieveUserProxyAgent(\n",
    "    human_input_mode=\"NEVER\",\n",
    "    llm_config = llm_mistral,\n",
    "    retrieve_config={\n",
    "        \"task\": \"code\",\n",
    "        \"docs_path\": \"/home/niel77/MechanicalAgents/data/Examples_small.md\",\n",
    "        \"client\": chromadb.PersistentClient(path=\"/tmp/chromadb\"),\n",
    "        \"get_or_create\": True,\n",
    "        \"overwrite\": False,  # Set to True if you want to overwrite existing collections\n",
    "        \"clean_up_tokenization_spaces\": True,\n",
    "    },\n",
    "    code_execution_config=False,\n",
    "    description = \"You are a retriever agent who codes in python to create 3D model in CadQuery\"\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Number of requested results 20 is greater than number of elements in index 1, updating n_results = 1\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "VectorDB returns doc_ids:  [['dd8041f2']]\n",
      "\u001b[32mAdding content of doc dd8041f2 to context.\u001b[0m\n",
      "\u001b[33mRetrieveChatAgent\u001b[0m (to user_proxy):\n",
      "\n",
      "You're a retrieve augmented coding assistant. You answer user's questions based on your own knowledge and the\n",
      "context provided by the user.\n",
      "If you can't answer the question with or without the current context, you should reply exactly `UPDATE CONTEXT`.\n",
      "For code generation, you must obey the following rules:\n",
      "Rule 1. You MUST NOT install any packages because all the packages needed are already installed.\n",
      "Rule 2. You must follow the formats below to write your code:\n",
      "```python\n",
      "# your code\n",
      "```\n",
      "\n",
      "User's question is: Write a Cadquery code to create a plate with hole.\n",
      "\n",
      "Context is: ﻿**CadQuery Documentation, Release 2.4.0![ref1]**\n",
      "\n",
      "1. **Simple Rectangular Plate**\n",
      "\n",
      "Just about the simplest possible example, a rectangular box result = cadquery.Workplane(\"front\").box(2.0, 2.0, 0.5)![](Aspose.Words.2df53558-1763-4492-a0d5-1196ef47bb5b.002.png)\n",
      "\n",
      "**Api References![](Aspose.Words.2df53558-1763-4492-a0d5-1196ef47bb5b.003.png)**\n",
      "\n",
      "- Workplane() **!** • Workplane.box() **!**\n",
      "2. **Plate with Hole**\n",
      "\n",
      "A rectangular box, but with a hole added.\n",
      "\n",
      "“>Z” selects the top most face of the resulting box. The hole is located in the center because the default origin of a working plane is the projected origin of the last Workplane, the last Workplane having origin at (0,0,0) the projection is at the center of the face. The default hole depth is through the entire part.\n",
      "\n",
      "- The dimensions of the box. These can be modified rather than changing the![](Aspose.Words.2df53558-1763-4492-a0d5-1196ef47bb5b.004.png)\n",
      "- object's code directly.\n",
      "\n",
      "length = 80.0\n",
      "\n",
      "height = 60.0\n",
      "\n",
      "thickness = 10.0\n",
      "\n",
      "center\\_hole\\_dia = 22.0\n",
      "\n",
      "- Create a box based on the dimensions above and add a 22mm center hole result = (\n",
      "\n",
      "cq.Workplane(\"XY\")\n",
      "\n",
      ".box(length, height, thickness)\n",
      "\n",
      ".faces(\">Z\")\n",
      "\n",
      ".workplane()\n",
      "\n",
      ".hole(center\\_hole\\_dia)\n",
      "\n",
      ")\n",
      "\n",
      "**Api References![](Aspose.Words.2df53558-1763-4492-a0d5-1196ef47bb5b.005.png)**\n",
      "\n",
      "- Workplane.hole() **!** • Workplane.box()\n",
      "- Workplane.box()\n",
      "3. **An extruded prismatic solid**\n",
      "\n",
      "Build a prismatic solid using extrusion. After a drawing operation, the center of the previous object is placed on the stack, and is the reference for the next operation. So in this case, the rect() is drawn centered on the previously draw circle.\n",
      "\n",
      "By default, rectangles and circles are centered around the previous working point. result = cq.Workplane(\"front\").circle(2.0).rect(0.5, 0.75).extrude(0.5)![](Aspose.Words.2df53558-1763-4492-a0d5-1196ef47bb5b.006.png)![ref2]\n",
      "\n",
      "**68 Chapter 3. Table Of Contents**\n",
      "\n",
      "\n",
      "**CadQuery Documentation, Release 2.4.0![ref1]**\n",
      "\n",
      "**Api References![](Aspose.Words.2df53558-1763-4492-a0d5-1196ef47bb5b.008.png)**\n",
      "\n",
      "- Workplane.circle() **!** • Workplane.extrude() **!**\n",
      "- Workplane.rect() **!** • Workplane()\n",
      "4. **Building Profiles using lines and arcs**\n",
      "\n",
      "Sometimes you need to build complex profiles using lines and arcs. This example builds a prismatic solid from 2D operations.\n",
      "\n",
      "2D operations maintain a current point, which is initially at the origin. Use close() to finisha closed curve. result = (![](Aspose.Words.2df53558-1763-4492-a0d5-1196ef47bb5b.009.png)\n",
      "\n",
      "cq.Workplane(\"front\")\n",
      "\n",
      ".lineTo(2.0, 0)\n",
      "\n",
      ".lineTo(2.0, 1.0) .threePointArc((1.0, 1.5), (0.0, 1.0)) .close()\n",
      "\n",
      ".extrude(0.25)\n",
      "\n",
      ")\n",
      "\n",
      "**Api References![](Aspose.Words.2df53558-1763-4492-a0d5-1196ef47bb5b.010.png)**\n",
      "\n",
      "- Workplane.threePointArc() **!** • Workplane.extrude()\n",
      "- Workplane.lineTo() **!** • Workplane()\n",
      "5. **Moving The Current working point**\n",
      "\n",
      "In this example, a closed profileis required, with some interior features as well.\n",
      "\n",
      "This example also demonstrates using multiple lines of code instead of longer chained commands, though of course in this case it was possible to do it in one long line as well.\n",
      "\n",
      "A new work plane center can be established at any point.\n",
      "\n",
      "result = cq.Workplane(\"front\").circle(![](Aspose.Words.2df53558-1763-4492-a0d5-1196ef47bb5b.011.png)\n",
      "\n",
      "3\\.0\n",
      "\n",
      ") # current point is the center of the circle, at (0, 0)\n",
      "\n",
      "result = result.center(1.5, 0.0).rect(0.5, 0.5) # new work center is (1.5, 0.0)\n",
      "\n",
      "result = result.center(-1.5, 1.5).circle(0.25) # new work center is (0.0, 1.5).\n",
      "\n",
      "- The new center is specified relative to the previous center, not global coordinates!\n",
      "\n",
      "result = result.extrude(0.25)\n",
      "\n",
      "**Api References![](Aspose.Words.2df53558-1763-4492-a0d5-1196ef47bb5b.012.png)![ref2]**\n",
      "\n",
      "**3.10. Examples 69**\n",
      "\n",
      "**CadQuery Documentation, Release 2.4.0![ref1]**\n",
      "\n",
      "- Workplane.center() **!** • Workplane.rect()![](Aspose.Words.2df53558-1763-4492-a0d5-1196ef47bb5b.013.png)\n",
      "- Workplane() • Workplane.extrude()\n",
      "- Workplane.circle()\n",
      "6. **Using Point Lists**\n",
      "\n",
      "Sometimes you need to create a number of features at various locations, and using Workplane.center() is too cumbersome.\n",
      "\n",
      "You can use a list of points to construct multiple objects at once. Most construction methods, like Workplane. circle() and Workplane.rect() , will operate on multiple points if they are on the stack\n",
      "\n",
      "r = cq.Workplane(\"front\").circle(2.0) # make base![](Aspose.Words.2df53558-1763-4492-a0d5-1196ef47bb5b.014.png)\n",
      "\n",
      "r = r.pushPoints(\n",
      "\n",
      "[(1.5, 0), (0, 1.5), (-1.5, 0), (0, -1.5)]\n",
      "\n",
      ") # now four points are on the stack\n",
      "\n",
      "r = r.circle(0.25) # circle will operate on all four points result = r.extrude(0.125) # make prism\n",
      "\n",
      "**Api References![](Aspose.Words.2df53558-1763-4492-a0d5-1196ef47bb5b.015.png)**\n",
      "\n",
      "- Workplane.pushPoints() **!** • Workplane.circle()\n",
      "- Workplane() • Workplane.extrude()\n",
      "7. **Polygons**\n",
      "\n",
      "You can create polygons for each stack point if you would like. Useful in 3d printers whose firmware does not correct for small hole sizes.\n",
      "\n",
      "result = (![](Aspose.Words.2df53558-1763-4492-a0d5-1196ef47bb5b.016.png)\n",
      "\n",
      "cq.Workplane(\"front\")\n",
      "\n",
      ".box(3.0, 4.0, 0.25) .pushPoints([(0, 0.75), (0, -0.75)]) .polygon(6, 1.0)\n",
      "\n",
      ".cutThruAll()\n",
      "\n",
      ")\n",
      "\n",
      "**Api References![](Aspose.Words.2df53558-1763-4492-a0d5-1196ef47bb5b.017.png)**\n",
      "\n",
      "- Workplane.polygon() **!** • Workplane.box()\n",
      "- Workplane.pushPoints()![ref2]\n",
      "\n",
      "**70 Chapter 3. Table Of Contents**\n",
      "\n",
      "[ref1]: Aspose.Words.2df53558-1763-4492-a0d5-1196ef47bb5b.001.png\n",
      "[ref2]: Aspose.Words.2df53558-1763-4492-a0d5-1196ef47bb5b.007.png\n",
      "\n",
      "\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "\u001b[31m\n",
      ">>>>>>>> EXECUTING CODE BLOCK 0 (inferred language is python)...\u001b[0m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[33muser_proxy\u001b[0m (to RetrieveChatAgent):\n",
      "\n",
      "exitcode: 0 (execution succeeded)\n",
      "Code output: \n",
      "\n",
      "\n",
      "--------------------------------------------------------------------------------\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "ChatResult(chat_id=None, chat_history=[{'content': 'You\\'re a retrieve augmented coding assistant. You answer user\\'s questions based on your own knowledge and the\\ncontext provided by the user.\\nIf you can\\'t answer the question with or without the current context, you should reply exactly `UPDATE CONTEXT`.\\nFor code generation, you must obey the following rules:\\nRule 1. You MUST NOT install any packages because all the packages needed are already installed.\\nRule 2. You must follow the formats below to write your code:\\n```python\\n# your code\\n```\\n\\nUser\\'s question is: Write a Cadquery code to create a plate with hole.\\n\\nContext is: \\ufeff**CadQuery Documentation, Release 2.4.0![ref1]**\\n\\n1. **Simple Rectangular Plate**\\n\\nJust about the simplest possible example, a rectangular box result = cadquery.Workplane(\"front\").box(2.0, 2.0, 0.5)![](Aspose.Words.2df53558-1763-4492-a0d5-1196ef47bb5b.002.png)\\n\\n**Api References![](Aspose.Words.2df53558-1763-4492-a0d5-1196ef47bb5b.003.png)**\\n\\n- Workplane() **!** • Workplane.box() **!**\\n2. **Plate with Hole**\\n\\nA rectangular box, but with a hole added.\\n\\n“>Z” selects the top most face of the resulting box. The hole is located in the center because the default origin of a working plane is the projected origin of the last Workplane, the last Workplane having origin at (0,0,0) the projection is at the center of the face. The default hole depth is through the entire part.\\n\\n- The dimensions of the box. These can be modified rather than changing the![](Aspose.Words.2df53558-1763-4492-a0d5-1196ef47bb5b.004.png)\\n- object\\'s code directly.\\n\\nlength = 80.0\\n\\nheight = 60.0\\n\\nthickness = 10.0\\n\\ncenter\\\\_hole\\\\_dia = 22.0\\n\\n- Create a box based on the dimensions above and add a 22mm center hole result = (\\n\\ncq.Workplane(\"XY\")\\n\\n.box(length, height, thickness)\\n\\n.faces(\">Z\")\\n\\n.workplane()\\n\\n.hole(center\\\\_hole\\\\_dia)\\n\\n)\\n\\n**Api References![](Aspose.Words.2df53558-1763-4492-a0d5-1196ef47bb5b.005.png)**\\n\\n- Workplane.hole() **!** • Workplane.box()\\n- Workplane.box()\\n3. **An extruded prismatic solid**\\n\\nBuild a prismatic solid using extrusion. After a drawing operation, the center of the previous object is placed on the stack, and is the reference for the next operation. So in this case, the rect() is drawn centered on the previously draw circle.\\n\\nBy default, rectangles and circles are centered around the previous working point. result = cq.Workplane(\"front\").circle(2.0).rect(0.5, 0.75).extrude(0.5)![](Aspose.Words.2df53558-1763-4492-a0d5-1196ef47bb5b.006.png)![ref2]\\n\\n**68 Chapter 3. Table Of Contents**\\n\\n\\n**CadQuery Documentation, Release 2.4.0![ref1]**\\n\\n**Api References![](Aspose.Words.2df53558-1763-4492-a0d5-1196ef47bb5b.008.png)**\\n\\n- Workplane.circle() **!** • Workplane.extrude() **!**\\n- Workplane.rect() **!** • Workplane()\\n4. **Building Profiles using lines and arcs**\\n\\nSometimes you need to build complex profiles using lines and arcs. This example builds a prismatic solid from 2D operations.\\n\\n2D operations maintain a current point, which is initially at the origin. Use close() to finisha closed curve. result = (![](Aspose.Words.2df53558-1763-4492-a0d5-1196ef47bb5b.009.png)\\n\\ncq.Workplane(\"front\")\\n\\n.lineTo(2.0, 0)\\n\\n.lineTo(2.0, 1.0) .threePointArc((1.0, 1.5), (0.0, 1.0)) .close()\\n\\n.extrude(0.25)\\n\\n)\\n\\n**Api References![](Aspose.Words.2df53558-1763-4492-a0d5-1196ef47bb5b.010.png)**\\n\\n- Workplane.threePointArc() **!** • Workplane.extrude()\\n- Workplane.lineTo() **!** • Workplane()\\n5. **Moving The Current working point**\\n\\nIn this example, a closed profileis required, with some interior features as well.\\n\\nThis example also demonstrates using multiple lines of code instead of longer chained commands, though of course in this case it was possible to do it in one long line as well.\\n\\nA new work plane center can be established at any point.\\n\\nresult = cq.Workplane(\"front\").circle(![](Aspose.Words.2df53558-1763-4492-a0d5-1196ef47bb5b.011.png)\\n\\n3\\\\.0\\n\\n) # current point is the center of the circle, at (0, 0)\\n\\nresult = result.center(1.5, 0.0).rect(0.5, 0.5) # new work center is (1.5, 0.0)\\n\\nresult = result.center(-1.5, 1.5).circle(0.25) # new work center is (0.0, 1.5).\\n\\n- The new center is specified relative to the previous center, not global coordinates!\\n\\nresult = result.extrude(0.25)\\n\\n**Api References![](Aspose.Words.2df53558-1763-4492-a0d5-1196ef47bb5b.012.png)![ref2]**\\n\\n**3.10. Examples 69**\\n\\n**CadQuery Documentation, Release 2.4.0![ref1]**\\n\\n- Workplane.center() **!** • Workplane.rect()![](Aspose.Words.2df53558-1763-4492-a0d5-1196ef47bb5b.013.png)\\n- Workplane() • Workplane.extrude()\\n- Workplane.circle()\\n6. **Using Point Lists**\\n\\nSometimes you need to create a number of features at various locations, and using Workplane.center() is too cumbersome.\\n\\nYou can use a list of points to construct multiple objects at once. Most construction methods, like Workplane. circle() and Workplane.rect() , will operate on multiple points if they are on the stack\\n\\nr = cq.Workplane(\"front\").circle(2.0) # make base![](Aspose.Words.2df53558-1763-4492-a0d5-1196ef47bb5b.014.png)\\n\\nr = r.pushPoints(\\n\\n[(1.5, 0), (0, 1.5), (-1.5, 0), (0, -1.5)]\\n\\n) # now four points are on the stack\\n\\nr = r.circle(0.25) # circle will operate on all four points result = r.extrude(0.125) # make prism\\n\\n**Api References![](Aspose.Words.2df53558-1763-4492-a0d5-1196ef47bb5b.015.png)**\\n\\n- Workplane.pushPoints() **!** • Workplane.circle()\\n- Workplane() • Workplane.extrude()\\n7. **Polygons**\\n\\nYou can create polygons for each stack point if you would like. Useful in 3d printers whose firmware does not correct for small hole sizes.\\n\\nresult = (![](Aspose.Words.2df53558-1763-4492-a0d5-1196ef47bb5b.016.png)\\n\\ncq.Workplane(\"front\")\\n\\n.box(3.0, 4.0, 0.25) .pushPoints([(0, 0.75), (0, -0.75)]) .polygon(6, 1.0)\\n\\n.cutThruAll()\\n\\n)\\n\\n**Api References![](Aspose.Words.2df53558-1763-4492-a0d5-1196ef47bb5b.017.png)**\\n\\n- Workplane.polygon() **!** • Workplane.box()\\n- Workplane.pushPoints()![ref2]\\n\\n**70 Chapter 3. Table Of Contents**\\n\\n[ref1]: Aspose.Words.2df53558-1763-4492-a0d5-1196ef47bb5b.001.png\\n[ref2]: Aspose.Words.2df53558-1763-4492-a0d5-1196ef47bb5b.007.png\\n\\n', 'role': 'assistant', 'name': 'RetrieveChatAgent'}, {'content': 'exitcode: 0 (execution succeeded)\\nCode output: \\n', 'role': 'user', 'name': 'user_proxy'}], summary='exitcode: 0 (execution succeeded)\\nCode output: \\n', cost={'usage_including_cached_inference': {'total_cost': 0}, 'usage_excluding_cached_inference': {'total_cost': 0}}, human_input=[])"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "rag_agent.initiate_chat(user_proxy, message=rag_agent.message_generator, problem=\"Write a Cadquery code to create a plate with hole.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "magents",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
